name: Hello World
author: Demola Adebayo
description: Some description
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: Demola
outputs:
  time:
    description: "The greeting time"
runs:
  using: "node16"
  main: "dist/index.js"