name: Notify on Issue
on:
  issues:
    types: [opened]

jobs:
  slack-message:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Message
        run: |
          echo "New issue created: <${{ github.event.issue.html_url }}|${{
          github.event.issue.title}}.>"}
