name: Get workflow information

on:
  push:
    branches:
      - workflow
  pull_request:
    branches:
      - workflow

permissions:
  actions: read
  checks: write
  contents: read
  issues: read
  pull-requests: write

jobs:
  logger-info:
    runs-on: ubuntu-latest
    name: Workflow information i.e start time
    steps:
      - uses: actions/checkout@v2

      # - name: Inspect context
      #   run: |
      #     echo "The github context is:"
      #     echo "${{ toJson(github) }}"
      #     echo ""
      #     echo "The job context is:"
      #     echo "${{ toJson(job) }}"
      #     echo ""
      #     echo "The steps context is:"
      #     echo "${{ toJson(steps) }}"
      #     echo ""
      #     echo "The runner context is:"
      #     echo "${{ toJson(runner) }}"
      #     echo ""
      #     echo "The strategy context is:"
      #     echo "${{ toJson(strategy) }}"
      #     echo ""
      #     echo "The matrix context is:"
      #     echo "${{ toJson(matrix) }}"
      #     echo This workflow on ${{ github.repository }} was started by ${{ github.actor }}

      # - name: example job
      #   id: gotit
      #   run: |
      #     `curl \
      #      -H "Accept: application/vnd.github.v3+json" \
      #      https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}`

      - name: Calculate Workflow run
        id: display
        run: |
          MY_OUTPUT=`curl \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}`
          echo "::set-output name=content::$MY_OUTPUT"

      - name: Run Custom Action
        uses: ./.github/actions/custom
        id: query
        with:
          token: ${{ secrets.GHA_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          run_id: ${{ github.run_id }}
          attempt_number: ${{ github.run_attempt }}

      - name: Spit out outputs
        run: |
          echo "HTML_URL: ${{ steps.query.outputs.html_url }}"
          echo "Conclusion: ${{ steps.query.outputs.conclusion }}"
          echo "completed_at: ${{ steps.query.outputs.completed_at }}"
          echo "started_at: ${{ steps.query.outputs.started_at }}"
