name: Get workflow information

on:
  pull_request:

permissions:
  actions: read
  checks: write
  contents: read
  issues: read
  pull-requests: write

jobs:
  logger-info:
    runs-on: ubuntu-latest
    name: Workflow information i.e start time
    steps:
      - uses: actions/checkout@v2

      - name: Run Custom Action
        uses: ./.github/actions/custom
        id: query
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          run_id: ${{ github.run_id }}
          attempt_number: ${{ github.run_attempt }}

      - name: Spit out outputs
        run: |
          echo "Repo: ${{ steps.query.outputs.repo }}"
          echo "Owner: ${{ steps.query.outputs.owner }}"
          echo "Run Id: ${{ steps.query.outputs.run_id }}"
          echo "Response: ${{ steps.query.outputs.response }}"
